### ISSUE TITLE
File Path Overlapping Main Content

### ISSUE THREAD

**Issue by Alex-Rafter** [mflorence99/lintel#14]
The file path text slightly overlaps the main content (example image uploaded). 

There seems to be a different z-index value (or its equivalent) given to some of the main content areas. Some of the checkboxes sit on top of the file path text and are less affected than certain paragraphs, which lie underneath the file path text. 

Tested on 1280px by 720px screen.

![lintel-screen](https://user-images.githubusercontent.com/42029575/86044392-f38d8480-ba41-11ea-917a-3f870707aefb.jpg)

**Comment by mflorence99** [comment]
Crap! Many thanks, Alex for your feedback. All that 'clever' I added code to elide the longest common prefix of a set of `.eslintrc` files -- as you would see in a multi-root project -- *does not work when there's only one file*. Doh! What I meant to show in your case was just the file name, less that path. I'll fix that right away and add a unit test.

**Comment by mflorence99** [comment]
Ah! I see from the code that more accurately I didn't cater for Windows paths. I'm just looking for `/` as a delimiter and not `\`. The clue is that the `\` path separators are completely missing in the UI. They're being handled as escapes.

**Comment by mflorence99** [comment]
Fixed in 1.0.4.
