### ISSUE TITLE
Can't "edit other settings" in Windows

### ISSUE THREAD

**Issue by mflorence99** [mflorence99/lintel#27]
As reported by @jerone.

```
[2020-11-09 16:27:09.068] [renderer1] [error] cannot open c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json. Detail: Unable to resolve resource c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json: Error: cannot open c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json. Detail: Unable to resolve resource c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json
```

**Comment by mflorence99** [comment]
@jerone I can see that `Uri.parse` and `Uri.file` produce different results for Windows paths, but not for Linux or Mac paths. I'm using `Uri.parse` and I can't see any hints in the docs that might explain the difference, although I can see the difference might account for the bug you report.

If I built with `Uri.file` would you be willing to give it a try?

Many thanks for your help and patience!

**Comment by jerone** [comment]
> If I built with `Uri.file` would you be willing to give it a try?

Yes of course. That will be tomorrow; it's bed time for me.

If there are some clear instructions in how to run a debug version of this extension, I can try master or any other branch...

**Comment by mflorence99** [comment]
You bet, understood! I'll just do a regular deploy -- that will be tomorrow
for me too as I can't do it this evening -- of v1.3.2 so that the workload
for you is minimal, It is safe because my tests show that Linux and Mac
work either way.

**Comment by mflorence99** [comment]
v1.3.2 is now available. It uses `Uri.file` rather than 'Uri.parse` to prepare a file name for `window.showTextDocument`.

Again, many thanks for your interest and patience. Later, I hope to release a fix for #26.

**Comment by jerone** [comment]
Confirmed fixed. Great work 💪

**Comment by mflorence99** [comment]
Many thanks for your help @jerone!
