### ISSUE TITLE
Possible unrecognized rules

### ISSUE THREAD

**Issue by mflorence99** [mflorence99/lintel#28]
@jerone requests:

Any chance to recognize the rules from (new issue?):
    *   @typescript-eslint ➡ https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
    *   @angular-eslint ➡ https://github.com/angular-eslint/angular-eslint#rules-list
    *   Prettier ➡ https://github.com/prettier/eslint-config-prettier (aldo this package only turns off all rules that are unnecessary or might conflict with [Prettier](https://github.com/prettier/prettier)).

**Comment by mflorence99** [comment]
@jerone Could you explain a bit more what you see when these rules are not recognized? I use them a lot in my testing and I see them. A screenshot might help. Do you have the plugins actually installed? If not, Lintel will show them under an "Unknown" tab.

Many thanks!

**Comment by jerone** [comment]
@mflorence99 This is what I see:

![](https://user-images.githubusercontent.com/55841/98683893-db216500-2365-11eb-9ce3-2783d5031294.png)

![](https://user-images.githubusercontent.com/55841/98684173-276ca500-2366-11eb-9363-67a60bc4d2b5.png)

None of the [@typescript-eslint](https://github.com/typescript-eslint) and @angular-eslint rules are recognized.

All plugins are installed; this is from my `package.json`:

```
		"@angular-eslint/builder": "0.6.0-beta.0",
		"@angular-eslint/eslint-plugin": "0.6.0-beta.0",
		"@angular-eslint/eslint-plugin-template": "0.6.0-beta.0",
		"@angular-eslint/schematics": "^0.6.0-beta.0",
		"@angular-eslint/template-parser": "0.6.0-beta.0",
		"@typescript-eslint/eslint-plugin": "^4.7.0",
		"@typescript-eslint/parser": "^4.7.0",
		"eslint": "^7.13.0",
		"eslint-config-prettier": "^6.15.0",
		"eslint-plugin-prettier": "^3.1.4",
```

Happy to support more information if needed...

**Comment by mflorence99** [comment]
Got it, thanks

**Comment by mflorence99** [comment]
Should be fixed in v1.3.3, available now.

**Comment by jerone** [comment]
Awesome work @mflorence99, all rules are recognized now.

**Comment by mflorence99** [comment]
All thanks to you and your help. Many thanks again!
